from models import user
from models import class_group
from models import student
from models import teacher
from models import attendance
from models import attendance_raw
from models import subscription
from models import schedule
from models import settings
from models import exam
from models import expense